# Generated by Django 4.1.7 on 2023-04-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_description_alter_task_executor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_update',
        ),
    ]
