# Generated by Django 4.1.7 on 2023-03-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_labels'),
        ('tags', '0002_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
