# Generated by Django 4.1.7 on 2023-04-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='date_update',
        ),
    ]
