on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: ^3.10
        
    - name: Installation of dependencies
      run: |
          pip install poetry
          make install
      
    - name: Run coverage  
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      with:
         coverageCommand: make tests-coverage