# Generated by Django 4.1.7 on 2023-03-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_time_create_status_date_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
    ]
